services:
    authorization_command:
        class: Hanaboso\PipesPhpSdk\Command\AuthorizeUserCommand
        tags: [console.command]
        arguments:
            - '@hbpf.application.manager'
            - '@doctrine_mongodb.odm.default_document_manager'