parameters:
    mongo_host: mongo

doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    auto_generate_persistent_collection_classes: 3
    proxy_namespace: Proxies
    proxy_dir: "%kernel.cache_dir%/doctrine/odm/mongodb/Proxies"
    hydrator_namespace: Hydrators
    hydrator_dir: "%kernel.cache_dir%/doctrine/odm/mongodb/Hydrators"
    connections:
        default:
            server: "mongodb://%mongo_host%"
            options:
                connectTimeoutMS: 5000
                socketTimeoutMS: 5000
    default_database: pipes-php-sdk
    document_managers:
        default:
            mappings:
                CommonsDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../vendor/hanaboso/commons-bundle/src/Document"
                    prefix: Hanaboso\CommonsBundle\Document
                AuthorizationDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/Authorization/Document"
                    prefix: Hanaboso\PipesPhpSdk\Authorization\Document
                LongRunningNodeDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/LongRunningNode/Document"
                    prefix: Hanaboso\PipesPhpSdk\LongRunningNode\Document
                FileDocument:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../vendor/hanaboso/commons-bundle/src/FileStorage/Document"
                    prefix: Hanaboso\CommonsBundle\FileStorage\Document
                FileMongo:
                    type: annotation
                    is_bundle: false
                    dir: "%kernel.root_dir%/../vendor/hanaboso/commons-bundle/src/FileStorage/Driver/Impl/Mongo"
                    prefix: Hanaboso\CommonsBundle\FileStorage\Driver\Impl\Mongo