version: '3.5'
services:
    php-dev:
        image: hanabosocom/php-dev:php-7.4
        user: ${DEV_UID}:${DEV_GID}
        ports:
            - ${DEV_IP}:8000:80
        volumes:
            - ./:/var/www
            - ${SSH_AUTH_SOCK}:${SSH_AUTH}
            - ${HOME}/dev/.composer:${HOME}/dev/.composer
        environment:
            - DEV_UID=${DEV_UID}
            - DEV_GID=${DEV_GID}
            - KERNEL_CLASS=Hanaboso\PipesPhpSdk\Kernel
            - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
            - COMPOSER_HOME=${HOME}/dev/.composer
            - METRICS_SERVICE=mongo

    mongo:
        image: mongo:latest
        ports:
            - ${DEV_IP}:27017:27017
        volumes:
            - mongo:/data/db

volumes:
    mongo: {}
