services:
    app:
        image: hanabosocom/php-dev:php-8.4-alpine
        user: ${DEV_UID}:${DEV_GID}
        ports:
            - ${DEV_IP}:80:80
        volumes:
            - ./:/var/www:cached
            - ${SSH_AUTH}:/tmp/.ssh-auth-sock
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached
        environment:
            - DEV_UID=${DEV_UID}
            - DEV_GID=${DEV_GID}
            - PHP_WEBROOT=/var/www/tests/app/public
            - KERNEL_CLASS=PipesPhpSdkTests\app\Kernel
            - COMPOSER_HOME=${HOME}/dev/.composer
            - WORKER_API=https://test.com
            - ORCHESTY_API_KEY=ThisIsNotRealKEy

    swagger-ui:
        image: swaggerapi/swagger-ui
        ports:
            - ${DEV_IP}:8080:8080
        volumes:
            - ./openapi.yaml:/api.yaml
        environment:
            SWAGGER_JSON: /api.yaml

volumes:
    mongo: {}
