services:
    _defaults:
        public: '%public.services%'

    hbpf.mapper.loader.mapper:
        class: Hanaboso\PipesPhpSdk\HbPFMapperBundle\Loader\MapperLoader
        public: true
        arguments:
            - '@service_container'

    hbpf.mapper.handler.mapper:
        class: Hanaboso\PipesPhpSdk\HbPFMapperBundle\Handler\MapperHandler
        arguments:
            - '@hbpf.mapper.loader.mapper'

    hbpf.mapper.null:
        class: Hanaboso\PipesPhpSdk\Mapper\Impl\NullMapper
        arguments:
