services:
    _defaults:
        public: '%public.services%'

    Hanaboso\PipesPhpSdk\HbPFJoinerBundle\Controller\JoinerController:
        class: Hanaboso\PipesPhpSdk\HbPFJoinerBundle\Controller\JoinerController
        arguments:
            - '@hbpf.handler.joiner'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]
