services:
    _defaults:
        public: '%public.services%'

    Hanaboso\PipesPhpSdk\HbPFApplicationBundle\Controller\ApplicationController:
        class: Hanaboso\PipesPhpSdk\HbPFApplicationBundle\Controller\ApplicationController
        arguments:
            - '@hbpf.application.handler'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]

    Hanaboso\PipesPhpSdk\HbPFApplicationBundle\Controller\WebhookController:
        class: Hanaboso\PipesPhpSdk\HbPFApplicationBundle\Controller\WebhookController
        arguments:
            - '@hbpf.application.handler.webhook'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]
