services:
    _defaults:
        public: '%public.services%'

    listener.repeater:
        class: Hanaboso\PipesPhpSdk\Listener\RepeaterListener
        calls:
            - ['setLogger', ['@monolog.logger.commons']]
        tags:
            - { name: kernel.event_subscriber }
        arguments:
          [ '@hbpf.node.repository' ]
