services:
    _defaults:
        public: '%public.services%'

    hbpf.authorization.handler:
        class: Hanaboso\PipesPhpSdk\HbPFAuthorizationBundle\Handler\ApplicationHandler
        arguments:
            - '@hbpf.authorization.manager'