services:
    _defaults:
        public: '%public.services%'

    hbpf.loader.long_running:
        class: Hanaboso\PipesPhpSdk\HbPFLongRunningNodeBundle\Loader\LongRunningNodeLoader
        arguments:
            - '@service_container'

    hbpf.listener.long_running:
        class: Hanaboso\PipesPhpSdk\HbPFLongRunningNodeBundle\Listener\LongRunningNodeListener
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
        tags:
            - { name: kernel.event_subscriber }

    hbpf.filter.long_running:
        class: Hanaboso\PipesPhpSdk\LongRunningNode\Model\LongRunningNodeFilter
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'

    hbpf.manager.long_running:
        class: Hanaboso\PipesPhpSdk\LongRunningNode\Model\LongRunningNodeManager
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'

    hbpf.handler.long_running:
        class: Hanaboso\PipesPhpSdk\HbPFLongRunningNodeBundle\Handler\LongRunningNodeHandler
        arguments:
            - '@hbpf.manager.long_running'
            - '@hbpf.loader.long_running'
            - '@hbpf.filter.long_running'
            - '@doctrine_mongodb.odm.default_document_manager'
